### ISSUE TITLE
Expected value for target `test` to be a list of dependency names.

### ISSUE THREAD

**Issue by margaeor** [1ozturkbe/OCTHaGOn.jl#114]
When I run the project using `julia --project=.` and then try to add dependencies to the project (i.e. using `add MyPackage`)
the following error appears:
```
Expected value for target `test` to be a list of dependency names
```
which prevents me from installing dependencies on the main package.
So, I temporarilly install my package-wide dependencies on the test
environment, which however I think is not correct.

**Comment by 1ozturkbe** [comment]
Huh, are you sure that you are up-to-date with the ```master``` branch? Because ```test``` is no longer in the dependencies.

**Comment by 1ozturkbe** [comment]
In addition, I am struggling to allow for an import of the package (of the for ```using OCTHaGOn```) that is not local (i.e. via ```include("src/OCTHaGOn.jl"); using .OCTHaGOn```). It will have to be a local import for the time being.

**Comment by 1ozturkbe** [comment]
In any case, let me know if this is still an issue. AFAIK, it has been solved.
